// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEKOB-2y02I6gn6avWdPMlU9gdLaik9jU',
    appId: '1:625963332142:web:f658073a114902075965bf',
    messagingSenderId: '625963332142',
    projectId: 'supabase-messenger',
    authDomain: 'supabase-messenger.firebaseapp.com',
    storageBucket: 'supabase-messenger.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5J80cwkMbrS7TosgV0xOdkJfwLbHSS_A',
    appId: '1:625963332142:android:a03f97a78b26c9565965bf',
    messagingSenderId: '625963332142',
    projectId: 'supabase-messenger',
    storageBucket: 'supabase-messenger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS98qVYCHY2dRdOuMv7_yilYgZfzeNVUM',
    appId: '1:625963332142:ios:c165ec8ee7a856085965bf',
    messagingSenderId: '625963332142',
    projectId: 'supabase-messenger',
    storageBucket: 'supabase-messenger.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce2',
  );
}
